### Home
GET http://localhost:5000/

### Obtener Productos
GET http://localhost:5000/Productos


### Crear Productos
POST http://localhost:5000/productos
Content-Type: application/json

{
    "image": "/images/filtro1.jpg",
    "title": "F6 F7 F8 F9 carton",
    "name": "producto 2",
    "price": 529.9
}

### Modificar Productos
PUT http://localhost:5000/productos/2
Content-Type: application/json

{
    "image": "/images/filtro1.jpg",
    "title": "F6 F7 F8 F9 carton",
    "name": "producto 2.1",
    "price": 529.9
}

### Eliminar Productos
DELETE http://localhost:5000/productos/1

### Obtener Productos
GET http://localhost:5000/productos/2

### Filtrar Productos
GET http://localhost:5000/productos/?filtro=F8